defaults: &defaults
  docker:
    # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
    - image: circleci/golang:1.13.1

  working_directory: /go/src/github.com/dikaeinstein/gomicroservice-infra-main

  environment:
    TEST_RESULTS: /tmp/test-results

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            curl -Ls -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.12/terraform_0.12.12_linux_amd64.zip
            sudo unzip /tmp/terraform.zip -d /usr/local/bin

      - run:
          name: Initialize Terraform
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=main.terraform

      - deploy:
          name: Deploy to AWS with Terraform
          command: terraform apply main.terraform

    filters:
      branches:
        only: master
